version: '3'
services:
  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/localtest
      #- MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}

    volumes:
      - ./backend/src:/app/src

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
